### ISSUE TITLE
finish graphql mappings

### ISSUE THREAD

**Issue by diegoquintanav** [diegoquintanav/pinochet-analyze-50#5]
# tasks

- [ ] add pagination and offset capabilities, see [graphql docs](https://strawberry.rocks/docs/guides/pagination/overview#implementing-pagination-in-graphql)
- [ ] add orm relationships between locations, events and persons, [see logrocket examples](https://blog.logrocket.com/using-graphql-strawberry-fastapi-next-js/#defining-sqlalchemy-models)
- [ ] add graphql mappings, see [logrocket examples](https://blog.logrocket.com/using-graphql-strawberry-fastapi-next-js/#defining-sqlalchemy-models) and [fastapi docs](https://fastapi.tiangolo.com/how-to/graphql/)
- [ ] document graphql better

**Comment by diegoquintanav** [comment]
closed by #9
